builds:
  - binary: ksedit
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
archive:
  format: binary
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
release:
  github:
    owner: Plaidev
    name: ksedit